import AboutSection from '@/components/AboutSection'
import Head from 'next/head'
import React from 'react'


const about = () => {
    return (
        <>
            <Head>
                <title>About Us | RoboSuperior</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <AboutSection />
        </>
    )
}

export default about