import Aside from '@/components/Aside'
import UserProfile from '@/components/userProfile'
import React, { useState, useEffect } from 'react'
import { useRouter } from 'next/router';
import Head from "next/head";

const Dashboard = () => {
  const router = useRouter();
  const [user, setUser] = useState({ value: null });

  useEffect(() => {
    const checkUser = () => {
      try {
        const token = localStorage.getItem("Token");
        if (token) {
          setUser({ value: token });
        } else {
          router.push('/'); // Redirect if no token is found
        }
      } catch (err) {
        console.error(err);
        // localstorage.clear();
        router.push('/'); // Redirect on error
      }
    };

    checkUser();
  }, [router]); // Adding router as a dependency

  // Early return or loading state if necessary
  if (user.value === null) {
    return null; // You can also show a loading spinner or placeholder here
  }

  return (
    <div>
      <Head>
        <title>Dashboard | RoboSuperior</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Aside />
      <UserProfile />
    </div>
  );
};

export default Dashboard;
